source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target ‘FETabBar’ do
    pod 'SnapKit', '~> 4.0.0'
end
